### ISSUE TITLE
Add parameter tables 

### ISSUE THREAD

**Issue by rekomodo** [festim-dev/V-V-report#29]
We can display parameters dynamically using MyST-NB's `{glue}` directive. We define variables in code cells  using `glue('name', value)` and use them in markdown via `` {glue}`name` `` .

Here's the code for dynamically adding trap variables to the document
```python
from myst_nb import glue

traps = [trap_1, trap_2, trap_3]

for i, trap in enumerate(traps):
    for key, value in trap.__dict__.items():
        glue(f'trap{i}{key}', value, display=False)
 ```

**Comment by RemDelaporteMathurin** [comment]
@rekomodo can you add the markdown code to display the values in a table pls?

**Comment by rekomodo** [comment]
Syntax from [this guide](https://www.markdownguide.org/extended-syntax/) .
The example I used was
```markdown
|Trap|k_0|E_k|p_0|...|
|:---|:--|:--|:--|:--|
|1|{glue}`trap1k_0`|{glue}`trap1E_k`|{glue}`trap1p_0`|...|
|2| ... and so on
```
Which renders to
|Trap|k_0|E_k|p_0|...|
|:---|:--|:--|:--|:--|
|1|{glue}`trap1k_0`|{glue}`trap1E_k`|{glue}`trap1p_0`|...|
|2|{glue}`trap2k_0`|{glue}`trap2E_k` | ... | ... |

We can definitely generate the markdown for these with a script if need be, but I doubt we'll need more than 3 anytime soon...

**Comment by rekomodo** [comment]
@RemDelaporteMathurin 
Noting that pandas data frames can be glued, as well as using sub commands to [format numbers](https://myst-nb.readthedocs.io/en/latest/render/glue.html#the-glue-text-role) and [**show sympy expressions as latex**](https://myst-nb.readthedocs.io/en/latest/render/glue.html#the-glue-math-directive)!. I'll be using these to clean up code later. Using these, the workflow for editing notebooks can be smoothed significantly and they'll be less error prone, since we could define equations once and avoid writing them.

**Comment by RemDelaporteMathurin** [comment]
@rekomodo I'm starting to wonder if it wouldn't be better to [display the values as a pandas dataframe](https://pandas.pydata.org/docs/user_guide/style.html#Formatting-Values)
