### ISSUE TITLE
Wrong thickness for Ogorodnikova's case?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/V-V-report#48]
I noticed that the thickness of the sample is 0.5 mm from the paper:
![image](https://github.com/festim-dev/V-V-report/assets/40028739/ab3d8df2-e7c4-4abc-842f-4db7cdc1b190)

but in the festim model we have 20 microns

https://github.com/festim-dev/V-V-report/blob/edf89c4c3171a173ddb1af77849489df53b37c8b/report/validation/thermodesorption_spectra/ogorodnikova/ogorodnikova-tds.md?plain=1#L54

Could this explain why we were struggling to reproduce #21 ?

**Comment by rekomodo** [comment]
I don't remember exactly why it didn't fit but,

using our mesh, [this implementation](https://github.com/gabriele-ferrero/Titans_TT_codecomparison/blob/main/Festim%20models/TDS_Tungsten.py) fits the first but not the second peak. Using their mesh (which covers all of the material) it fits both,

so it was definitely part of it, thanks for the feedback.

I can dig out the old implementation if you'd like though.

**Comment by RemDelaporteMathurin** [comment]
Not sure I'm following. What happens if we have the right dimensions in the current implementation in the code?

**Comment by rekomodo** [comment]
Our current implementation still works with the right dimensions.

**Comment by RemDelaporteMathurin** [comment]
> Strangely enough, the implementation you sent me has half the total fluence described in the paper.

Right. The fluence should be 1E23 H/m2 but in this implementation the ion flux is 1.25E19 H/m2/s and the exposure time is 4000s (which corresponds to 0.5E23 H/m2).

I suspect this is simply because they assumed a reflection coefficient of 0.5: not all incident particles are implanted in the material. The incident fluence is not calculated from the implanted particles but from the incident ones. 

We would need @gabriele-ferrero or @ehodille to confirm this

**Comment by rekomodo** [comment]
Think we can close this now? We got an explanation for these things.

**Comment by RemDelaporteMathurin** [comment]
is the actual thickness issue fixed?
