### ISSUE TITLE
Add instructions to convert myst files to python or ipynb

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [festim-dev/V-V-report#51]

**Comment by rekomodo** [comment]
I'd planned to include this in the "how to contribute" section of #49 .

**Comment by RemDelaporteMathurin** [comment]
> I'd planned to include this in the "how to contribute" section of #49 , although the readme might be a better place right?

I'd say both! 😄

**Comment by rekomodo** [comment]
Solved in #54 .
