### ISSUE TITLE
Issue on page /_tags/tag2.html

### ISSUE THREAD

**Issue by rekomodo** [festim-dev/V-V-report#61]
This shouldn't be showing up as a tag.

**Comment by RemDelaporteMathurin** [comment]
Can you explain the issue a bit more? maybe with screenshots?

**Comment by RemDelaporteMathurin** [comment]
![image](https://github.com/user-attachments/assets/db27540f-ec31-483b-8334-47cfb034f2f0)

This seems to be the issue

https://festim-vv-report.readthedocs.io/en/latest/how_to.html#final-touches

**Comment by RemDelaporteMathurin** [comment]
I asked [here ](https://github.com/melissawm/sphinx-tags/issues/105) if there was a way to ignore tags

**Comment by rekomodo** [comment]
Right, thank you. I'd added it from the webpage and forgot to add details.
