### ISSUE TITLE
Build BinderHub on push, or reduce build conditions

### ISSUE THREAD

**Issue by rekomodo** [festim-dev/V-V-report#68]
we could try this https://discourse.jupyter.org/t/tip-speed-up-binder-launches-by-pulling-github-content-in-a-binder-link-with-nbgitpuller/922
or I can figure out another way to open the binder post push, with a hook i suppose

**Comment by RemDelaporteMathurin** [comment]
Maybe that's a bit overkill since at some point the activity on this repo will slow down
